ureportplus.disableHttpSessionReportCache=false
ureportplus.disableFileProvider=false
ureportplus.fileStoreDir=/Users/zahui/Desktop/KinginT/ureport2/ureportfiles
ureportplus.debug=true
ureportplus.disableDesigner=false
